name: deploy to production-xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install && yarn run prod
      - name: deploy to server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.PRODUCTION_DEPLOY_REMOTE_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}